"""jero — an opinionated, msgspec-first ASGI micro-framework."""

from jero.background import BackgroundTasks
from jero.codecs import msgspec_decoder, msgspec_encoder
from jero.core import (
    Auth,
    BaseApp,
    BaseFactory,
    BasicAuth,
    BearerAuth,
    BytesResponse,
    Endpoint,
    EndpointMeta,
    ExceptionResponse,
    JSONResponse,
    OperationMeta,
    Resource,
    ResourceMeta,
    WiringError,
)
from jero.errors import (
    AuthenticationRequiredError,
    BaseHTTPError,
    ConflictError,
    DataclassHTTPError,
    ErrorBodyAdapter,
    ForbiddenError,
    GoneError,
    HTTPError,
    InternalServerError,
    MalformedRequestError,
    MethodNotAllowedError,
    NotFoundError,
    ParameterizedHTTPError,
    ParameterizedProblem,
    Problem,
    StructHTTPError,
    TooManyRequestsError,
    UnsupportedMediaTypeError,
    ValidationFailedError,
)
from jero.forms import FilePart, FormPart
from jero.headers import RawHeaders
from jero.links import Link, Location
from jero.openapi import ModelMeta, ResponseSpec, SecurityScheme, Tag
from jero.streaming import NDJSONStreamingResponse, ServerSentEvent, SSEResponse, StreamingResponse
from jero.structs import Struct
from jero.testing import FactoryHarness, TestClient, TestResponse, TestSSEEvent

__all__ = [
    "Auth",
    "AuthenticationRequiredError",
    "BackgroundTasks",
    "BaseApp",
    "BaseFactory",
    "BaseHTTPError",
    "BasicAuth",
    "BearerAuth",
    "BytesResponse",
    "ConflictError",
    "DataclassHTTPError",
    "Endpoint",
    "EndpointMeta",
    "ErrorBodyAdapter",
    "ExceptionResponse",
    "FactoryHarness",
    "FilePart",
    "ForbiddenError",
    "FormPart",
    "GoneError",
    "HTTPError",
    "InternalServerError",
    "JSONResponse",
    "Link",
    "Location",
    "MalformedRequestError",
    "MethodNotAllowedError",
    "ModelMeta",
    "NDJSONStreamingResponse",
    "NotFoundError",
    "OperationMeta",
    "ParameterizedHTTPError",
    "ParameterizedProblem",
    "Problem",
    "RawHeaders",
    "Resource",
    "ResourceMeta",
    "ResponseSpec",
    "SSEResponse",
    "SecurityScheme",
    "ServerSentEvent",
    "StreamingResponse",
    "Struct",
    "StructHTTPError",
    "Tag",
    "TestClient",
    "TestResponse",
    "TestSSEEvent",
    "TooManyRequestsError",
    "UnsupportedMediaTypeError",
    "ValidationFailedError",
    "WiringError",
    "msgspec_decoder",
    "msgspec_encoder",
]
