"""jero — an opinionated, msgspec-first ASGI micro-framework."""

from jero._middleware import CORS, HTTPMethod, NoHeaders, Request
from jero.background import BackgroundTasks
from jero.codecs import msgspec_decoder, msgspec_encoder
from jero.cookies import SetCookie
from jero.core import (
    Accepted,
    Auth,
    BaseApp,
    BaseFactory,
    BasicAuth,
    BearerAuth,
    BytesResponse,
    CookieAuth,
    Created,
    Endpoint,
    EndpointMeta,
    ExceptionResponse,
    HybridAuth,
    JSONResponse,
    NoContent,
    OperationMeta,
    Resource,
    ResourceMeta,
    WebSocketEndpoint,
    WiringError,
)
from jero.errors import (
    AuthenticationRequiredError,
    BaseHTTPError,
    ConflictError,
    DataclassHTTPError,
    ErrorBodyAdapter,
    ErrorReason,
    ForbiddenError,
    GoneError,
    HTTPError,
    InternalServerError,
    MalformedRequestError,
    MethodNotAllowedError,
    NotFoundError,
    ParameterizedHTTPError,
    ParameterizedProblem,
    Problem,
    StructHTTPError,
    TooManyRequestsError,
    UnsupportedMediaTypeError,
    ValidationFailedError,
)
from jero.forms import FilePart, FormPart
from jero.headers import RawHeaders
from jero.links import Link, Location
from jero.openapi import ModelMeta, ResponseSpec, ScalarConfig, SecurityScheme, Tag
from jero.streaming import NDJSONStreamingResponse, ServerSentEvent, SSEResponse, StreamingResponse
from jero.structs import Struct
from jero.websockets import Channel, WebSocket

__all__ = [
    "CORS",
    "Accepted",
    "Auth",
    "AuthenticationRequiredError",
    "BackgroundTasks",
    "BaseApp",
    "BaseFactory",
    "BaseHTTPError",
    "BasicAuth",
    "BearerAuth",
    "BytesResponse",
    "Channel",
    "ConflictError",
    "CookieAuth",
    "Created",
    "DataclassHTTPError",
    "Endpoint",
    "EndpointMeta",
    "ErrorBodyAdapter",
    "ErrorReason",
    "ExceptionResponse",
    "FilePart",
    "ForbiddenError",
    "FormPart",
    "GoneError",
    "HTTPError",
    "HTTPMethod",
    "HybridAuth",
    "InternalServerError",
    "JSONResponse",
    "Link",
    "Location",
    "MalformedRequestError",
    "MethodNotAllowedError",
    "ModelMeta",
    "NDJSONStreamingResponse",
    "NoContent",
    "NoHeaders",
    "NotFoundError",
    "OperationMeta",
    "ParameterizedHTTPError",
    "ParameterizedProblem",
    "Problem",
    "RawHeaders",
    "Request",
    "Resource",
    "ResourceMeta",
    "ResponseSpec",
    "SSEResponse",
    "ScalarConfig",
    "SecurityScheme",
    "ServerSentEvent",
    "SetCookie",
    "StreamingResponse",
    "Struct",
    "StructHTTPError",
    "Tag",
    "TooManyRequestsError",
    "UnsupportedMediaTypeError",
    "ValidationFailedError",
    "WebSocket",
    "WebSocketEndpoint",
    "WiringError",
    "msgspec_decoder",
    "msgspec_encoder",
]
